# Source: bucketrepo/templates/config-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: bucketrepo-config
  namespace: jx
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"bucketrepo-config","properties":[{"name":"config.yaml","question":"The bucket repository configuration","help":"The configuration file for the bucket repo","template":"http:\n    addr: \":8080\"\n    username: \"{{ extsecret \"secret/data/jenkins-x-bucketrepo\" \"username\" }}\"\n    password: \"{{ extsecret \"secret/data/jenkins-x-bucketrepo\" \"password\" }}\"\n    chartPath: \"charts\"\n\n{{- if and (hasKey .Requirements \"storage\") ( .Requirements.storage)  }}\n{{- range $key, $val := .Requirements.storage }}\n{{- if eq \"repository\" $val.name }}\nstorage:\n    enabled: true\n    bucket_url: \"{{ $val.url }}\"\n{{- end }}\n{{- end }}\n{{- else }}\nstorage:\n    bucket_url: \"\"\n{{- end }}\n\ncache:\n    base_dir: \"./\"\nrepositories:\n"}],"mandatory":true}'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: local
  data:
  - name: config.yaml
    key: config.yaml
    property: config.yaml
  template:
    metadata:
      annotations:
        config/checksum: b1eb5b332c28e00b23a7c5486d015e0d78c687616523821242086ddccd823a24
        meta.helm.sh/release-name: 'bucketrepo'
        secret.jenkins-x.io/schema-object: '{"name":"bucketrepo-config","properties":[{"name":"config.yaml","question":"The bucket repository configuration","help":"The configuration file for the bucket repo","template":"http:\n    addr: \":8080\"\n    username: \"{{ extsecret \"secret/data/jenkins-x-bucketrepo\" \"username\" }}\"\n    password: \"{{ extsecret \"secret/data/jenkins-x-bucketrepo\" \"password\" }}\"\n    chartPath: \"charts\"\n\n{{- if and (hasKey .Requirements \"storage\") ( .Requirements.storage)  }}\n{{- range $key, $val := .Requirements.storage }}\n{{- if eq \"repository\" $val.name }}\nstorage:\n    enabled: true\n    bucket_url: \"{{ $val.url }}\"\n{{- end }}\n{{- end }}\n{{- else }}\nstorage:\n    bucket_url: \"\"\n{{- end }}\n\ncache:\n    base_dir: \"./\"\nrepositories:\n"}],"mandatory":true}'
    type: Opaque
