apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        hazem-internship/golang-demo: true
        hazem-internship/jenkinsx: true
        hazem-internship/things-board: true
        hazem-internship/thingsboard: true
        hazem-internship/thingsboard1: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        hazem-internship/golang-demo: merge
        hazem-internship/jenkinsx: merge
        hazem-internship/things-board: merge
        hazem-internship/thingsboard: merge
        hazem-internship/thingsboard1: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - hazem-internship/jenkinsx
        - hazem-internship/golang-demo
        - hazem-internship/things-board
        - hazem-internship/thingsboard
        - hazem-internship/thingsboard1
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - hazem-internship/jenkinsx
        - hazem-internship/golang-demo
        - hazem-internship/things-board
        - hazem-internship/thingsboard
        - hazem-internship/thingsboard1
      target_url: http://lighthouse-jx.10.0.0.100.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
