apiVersion: gitops.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
  - name: jenkins-x-bucketrepo
    mandatory: true
    properties:
    - name: BASIC_AUTH_USER
      question: bucket repository user name
      help: The username used to authenticate with the bucket repository
      defaultValue: admin
    - name: BASIC_AUTH_PASS
      question: bucket repository password
      help: The password to authenticate with the bucket repository
      minLength: 5
      maxLength: 41
      generator: password
  - name: bucketrepo-config
    mandatory: true
    properties:
    - name: config.yaml
      question: The bucket repository configuration
      help: The configuration file for the bucket repo
      noMask: true
      template: |
        http:
            addr: ":8080"
            username: "{{ extsecret "secret/data/jenkins-x-bucketrepo" "username" }}"
            password: "{{ extsecret "secret/data/jenkins-x-bucketrepo" "password" }}"
            chartPath: "charts"

        {{- if and (hasKey .Requirements "storage") ( .Requirements.storage)  }}
        {{- range $key, $val := .Requirements.storage }}
        {{- if eq "repository" $val.name }}
        storage:
            enabled: true
            bucket_url: "{{ $val.url }}"
        {{- end }}
        {{- end }}
        {{- else }}
        storage:
            bucket_url: ""
        {{- end }}

        cache:
            base_dir: "./"
        repositories:


